### ISSUE TITLE
task definition one-off command concatenation error

### ISSUE THREAD

**Issue by Jlkan** [Selleo/cli#11]
```yml
- name: ECS Deployment
        env:
          AWS_REGION: eu-central-1
          ECS_CLUSTER: dm3-96de6f97
          ECS_SERVICE: dm3
          DOCKER_IMAGE: ${{ secrets.AWS_ECR_REGISTRY }}:${{ github.sha }}
        run: selleo aws ecs deploy --region $AWS_REGION --cluster $ECS_CLUSTER --service $ECS_SERVICE --docker-image $DOCKER_IMAGE --one-off 5afe1718-migrate
```
